### ISSUE TITLE
Refactor current write-host calls to write-* cmdlets

### ISSUE THREAD

**Issue by mzball-dt** [mzball-dt/utils#6]
## Reason

All scripts currently use write-host with colouring changes to denote meaning.
This limits users from choosing what level of feedback they want to receive.

## Task

- [ ] Review the scaffolding format used for current scripts for where write-host should be replaced with the alternatives
- [ ] Update the [template script](https://github.com/mzball-dt/utils/blob/master/templateScaffold.ps1)
- [ ] Refactor the extant scripts with the new write-* cmdlets

This _should_ be a straight forward task, perfect for someone who wants to dabble!
